THEMES = {
    "og_blue": {
        "root": "#445469",
        "fg": "#519aba",
        "primary": "#090b10",
        "secondary": "#0f111a"
    },
    "default_repocard": {
        "root": "#2f80ed",
        "fg": "#586069",
        "secondary": "#ffeeee",
        "primary": "#fffefe",
    },
    "dark": {
        "root": "#fff",
        "fg": "#79ff97",
        "secondary": "#252525",
        "primary": "#161616",
    },
    "radical": {
        "root": "#fe428e",
        "fg": "#f8d847",
        "secondary": "#201828",
        "primary": "#141321",
    },
    "merko": {
        "root": "#abd200",
        "fg": "#b7d364",
        "secondary": "#1a1f1b",
        "primary": "#0a0f0b",
    },
    "gruvbox": {
        "root": "#fabd2f",
        "fg": "#fe8019",
        "secondary": "#383838",
        "primary": "#282828",
    },
    "tokyonight": {
        "root": "#70a5fd",
        "fg": "#bf91f3",
        "secondary": "#2a2b37",
        "primary": "#1a1b27",
    },
    "onedark": {
        "root": "#e4bf7a",
        "fg": "#8eb573",
        "secondary": "#383c44",
        "primary": "#282c34",
    },
    "cobalt": {
        "root": "#e683d9",
        "fg": "#0480ef",
        "secondary": "#294559",
        "primary": "#193549",
    },
    "synthwave": {
        "root": "#e2e9ec",
        "fg": "#ef8539",
        "secondary": "#3b314a",
        "primary": "#2b213a",
    },
    "highcontrast": {
        "root": "#e7f216",
        "fg": "#00ffff",
        "secondary": "#111",
        "primary": "#000",
    },
    "dracula": {
        "root": "#ff6e96",
        "fg": "#79dafa",
        "secondary": "#383a46",
        "primary": "#282a36",
    },
    "prussian": {
        "root": "#bddfff",
        "fg": "#38a0ff",
        "secondary": "#183f55",
        "primary": "#172f45",
    },
    "monokai": {
        "root": "#eb1f6a",
        "fg": "#e28905",
        "secondary": "#283832",
        "primary": "#272822",
    },
    "vue": {
        "root": "#41b883",
        "fg": "#41b883",
        "secondary": "#fffefe",
        "primary": "#dfdede",
    },
    "vue-dark": {
        "root": "#41b883",
        "fg": "#41b883",
        "secondary": "#374859",
        "primary": "#273849",
    },
    "shades-of-purple": {
        "root": "#fad000",
        "fg": "#b362ff",
        "secondary": "#3d3b65",
        "primary": "#2d2b55",
    },
    "nightowl": {
        "root": "#c792ea",
        "fg": "#ffeb95",
        "secondary": "#112637",
        "primary": "#011627",
    },
    "buefy": {
        "root": "#ef2850",
        "fg": "#ff3860",
        "secondary": "#363636",
        "primary": "#262626",
    },
    "blue-green": {
        "root": "#d5a700",
        "fg": "#f5b700",
        "secondary": "#141f1f",
        "primary": "#040f0f",
    },
    "algolia": {
        "root": "#00AEFF",
        "fg": "#2DDE98",
        "secondary": "#151f3c",
        "primary": "#050F2C",
    },
    "great-gatsby": {
        "root": "#ffa726",
        "fg": "#ffb74d",
        "secondary": "#202020",
        "primary": "#000000",
    },
    "darcula": {
        "root": "#BA5F17",
        "fg": "#84628F",
        "secondary": "#BEBEBE",
        "primary": "#242424",
    },
    "bear": {
        "root": "#e03c8a",
        "fg": "#00AEFF",
        "secondary": "#bcb28d",
        "primary": "#1f2023",
    },
    "solarized-dark": {
        "root": "#268bd2",
        "fg": "#b58900",
        "secondary": "#859900",
        "primary": "#002b36",
    },
    "solarized-light": {
        "root": "#268bd2",
        "fg": "#b58900",
        "secondary": "#859900",
        "primary": "#fdf6e3",
    },
    "chartreuse-dark": {
        "root": "#7fff00",
        "fg": "#00AEFF",
        "secondary": "#fff",
        "primary": "#000",
    },
    "nord": {
        "root": "#81a1c1",
        "secondary": "#d8dee9",
        "fg": "#88c0d0",
        "primary": "#2e3440",
    },
    "gotham": {
        "root": "#2aa889",
        "fg": "#599cab",
        "secondary": "#99d1ce",
        "primary": "#0c1014",
    },
    "material-palenight": {
        "root": "#c792ea",
        "fg": "#89ddff",
        "secondary": "#a6accd",
        "primary": "#292d3e",
    },
    "graywhite": {
        "root": "#24292e",
        "fg": "#24292e",
        "secondary": "#24292e",
        "primary": "#ffffff",
    },
    "vision-friendly-dark": {
        "root": "#ffb000",
        "fg": "#785ef0",
        "secondary": "#ffffff",
        "primary": "#000000",
    },
    "ayu-mirage": {
        "root": "#f4cd7c",
        "fg": "#73d0ff",
        "secondary": "#c7c8c2",
        "primary": "#1f2430",
    },
    "midnight-purple": {
        "root": "#9745f5",
        "fg": "#9f4bff",
        "secondary": "#ffffff",
        "primary": "#000000",
    },
    "calm": {
        "root": "#e07a5f",
        "fg": "#edae49",
        "secondary": "#ebcfb2",
        "primary": "#373f51",
    },
    "flag-india": {
        "root": "#ff8f1c",
        "fg": "#250E62",
        "secondary": "#509E2F",
        "primary": "#ffffff",
    },
    "omni": {
        "root": "#FF79C6",
        "fg": "#e7de79",
        "secondary": "#E1E1E6",
        "primary": "#191622",
    },
    "react": {
        "root": "#61dafb",
        "fg": "#61dafb",
        "secondary": "#ffffff",
        "primary": "#20232a",
    },
    "jolly": {
        "root": "#ff64da",
        "fg": "#a960ff",
        "secondary": "#ffffff",
        "primary": "#291B3E",
    },
    "maroongold": {
        "root": "#F7EF8A",
        "fg": "#F7EF8A",
        "secondary": "#E0AA3E",
        "primary": "#260000",
    },
    "yeblu": {
        "root": "#ffff00",
        "fg": "#ffff00",
        "secondary": "#ffffff",
        "primary": "#002046",
    },
    "blueberry": {
        "root": "#82aaff",
        "fg": "#89ddff",
        "secondary": "#27e8a7",
        "primary": "#242938",
    },
    "slateorange": {
        "root": "#faa627",
        "fg": "#faa627",
        "secondary": "#ffffff",
        "primary": "#36393f",
    },
    "kacho_ga": {
        "root": "#bf4a3f",
        "fg": "#a64833",
        "secondary": "#d9c8a9",
        "primary": "#402b23",
    },
    "outrun": {
        "root": "#ffcc00",
        "fg": "#ff1aff",
        "secondary": "#8080ff",
        "primary": "#141439",
    },
    "ocean_dark": {
        "root": "#8957B2",
        "fg": "#FFFFFF",
        "secondary": "#92D534",
        "primary": "#151A28",
    },
    "city_lights": {
        "root": "#5D8CB3",
        "fg": "#4798FF",
        "secondary": "#718CA1",
        "primary": "#1D252C",
    },
    "github_dark": {
        "root": "#58A6FF",
        "fg": "#1F6FEB",
        "secondary": "#C3D1D9",
        "primary": "#0D1117",
    },
    "discord_old_blurple": {
        "root": "#7289DA",
        "fg": "#7289DA",
        "secondary": "#FFFFFF",
        "primary": "#2C2F33",
    }
}


CHOICES = ['og_blue', 'default_repocard', 'dark', 'radical', 'merko', 'gruvbox', 
'tokyonight', 'onedark', 'cobalt', 'synthwave', 'highcontrast', 'dracula', 'prussian', 
'monokai', 'vue', 'vue-dark', 'shades-of-purple', 'nightowl', 'buefy', 'blue-green', 
'algolia', 'great-gatsby', 'darcula', 'bear', 'solarized-dark', 'solarized-light', 
'chartreuse-dark', 'nord', 'gotham', 'material-palenight', 'graywhite', 'vision-friendly-dark', 
'ayu-mirage', 'midnight-purple', 'calm', 'flag-india', 'omni', 'react', 'jolly', 
'maroongold', 'yeblu', 'blueberry', 'slateorange', 'kacho_ga', 'outrun', 'ocean_dark', 
'city_lights', 'github_dark', 'discord_old_blurple']