"""Applications & Commands used in afterlife"""

NATIVE_APPS = {
    "System Settings": [
        dict(event="start", label="Settings", query="start ms-settings:"),
        dict(event="start", label="Action Center", query="start ms-actioncenter:"),
        dict(event="start", label="Available Networks", query="start ms-availablenetworks:"),
        dict(event="start", label="Device Discovery", query="start ms-settings-connectabledevices:devicediscovery"),
    ],
    "Most Used": [
        dict(event="start", label="Alarms & Clock", query="start ms-clock:"),
        dict(event="start", label="Calculator", query="start calculator:"),
        dict(event="start", label="Calendar", query="start outlook cal:"),
        dict(event="start", label="Camera", query="start microsoft.windows.camera:"),
        dict(event="start", label="Drawboard PDF", query="start drawboardpdf:"),
        dict(event="start", label="Groove Music", query="start mswindowsmusic:"),
        dict(event="start", label="Mail", query="start outlookmail:"),
        dict(event="start", label="Microsoft Edge", query="start microsoft-edge:"),
        dict(event="start", label="Microsoft Whiteboard", query="start ms-whiteboard-cmd:"),
        dict(event="start", label="Movies & TV", query="start mswindowsvideo:"),
        dict(event="start", label="Photos", query="start ms-photos:"),
        dict(event="start", label="Screen Snip", query="start ms-screenclip:"),
        dict(event="start", label="Snip & Sketch", query="start ms-ScreenSketch:"),
        dict(event="start", label="Windows Security", query="start windowsdefender:"),
    ],
    "Least Used": [
        dict(event="start", label="3D Builder", query="start com.microsoft.builder3d:"),
        dict(event="start", label="3D Viewer", query="start com.microsoft.3dviewer:"),
        dict(event="start", label="Cortana", query="start ms-cortana:"),
        dict(event="start", label="Feedback Hub", query="start feedback-hub:"),
        dict(event="start", label="Get Help", query="start ms-contact-support:"),
        dict(event="start", label="Maps", query="start bingmaps:"),
        dict(event="start", label="Messaging", query="start ms-chat:"),
        dict(event="start", label="Microsoft News", query="start bingnews:"),
        dict(event="start", label="Microsoft Store", query="start ms-windows-store:"),
        dict(event="start", label="Paint 3D", query="start ms-paint:"),
        dict(event="start", label="People", query="start ms-people:"),
        dict(event="start", label="Tips", query="start ms-get-started:"),
        dict(event="start", label="Weather", query="start bingweather:"),
        dict(event="start", label="Xbox", query="start xbox:"),
    ]
}

ACTIONS = {
    0: [
        dict(label="Installed\nApps", command="start explorer.exe Shell:::AppsFolder"),
        dict(label="Root\nFolder", command="start explorer.exe Shell:::{59031a47-3f72-44a7-89c5-5595fe6b30ee}"),
        dict(label="Task\nManager", command="start taskmgr"),
        dict(label="Control\nPanel", command="start control"),
        dict(label="System\nSettings", command="start ms-settings:"),
    ],
    1: [
        dict(label="Google", command="url www.google.com"),
        dict(label="Gmail", command="url mail.google.com"),
        dict(label="Youtube", command="url www.youtube.com"),
        dict(label="Maps", command="url maps.google.com"),
        dict(label="Keep", command="url keep.google.com"),
    ],
    2: [
        dict(label="Docs", command="url docs.new"),
        dict(label="Sheets", command="url sheets.new"),
        dict(label="Slides", command="url slides.new"),
        dict(label="Notepad", command="start notepad"),
        dict(label="Sticky Notes", command="start explorer.exe shell:appsFolder\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App"),
    ],
    3: [
        dict(label="Web\nUtilities", command="url www.123apps.com"),
        dict(label="Cloud File\nConverter", command="url www.cloudconvert.com"),
        dict(label="Digital PDF\nTools", command="url www.smallpdf.com/pdf-tools"),
        dict(label="Online Photo\nEditor", command="url www.photopea.com"),
        dict(label="Net\nSpeed", command="url www.speedtest.net"),
    ],
    4: [
        dict(label="Spotify", command="url open.spotify.com"),
        dict(label="Bored\nButton", command="url www.boredbutton.com/random"),
        dict(label="Wikipedia", command="url www.wikipedia.org"),
        dict(label="Library\nGenesis", command="url libgen.rs/index.php"),
        dict(label="Good Reads", command="url www.readsomethinggreat.com"),
    ]
}

MENUS = {
    "CLIs": [
        dict(label="Command Prompt", command="start cmd /k cd /d %USERPROFILE%\Desktop"),
        dict(label="Command Prompt - Admin", command='start powershell "start cmd -v runAs"'),
        dict(label="Powershell", command="start powershell"),
        dict(label="WSL Bash", command="start bash"),
        "---",
        dict(label="Python", command="start python"),
        dict(label="Node", command="start node"),
    ],
    "Network": [
        dict(label="Ping", command="subprocess ping www.google.com"),
        "---",
        dict(label="List DNS Servers", command="subprocess ipconfig /displaydns"),
        dict(label="Initiate DNS Flush", command="subprocess ipconfig /flushdns"),
        "---",
        dict(label="Network Connections", command="subprocess netstat -an"),
        dict(label="IP Configurations", command="subprocess ipconfig /allcompartments /all"),
    ],
    "Advanced": [
        dict(label="System Info", command="subprocess systeminfo"),
        dict(label="Running Processes", command="subprocess tasklist"),
        dict(label="Environment Variables", command="subprocess set"),
        dict(label="Available Drivers", command="subprocess driverquery"),
        "---",
        dict(label="Installed Apps", command="start cmd /k wmic product get name,version"),
        "---",
        dict(label="Run", command="start explorer.exe Shell:::{2559a1f3-21d7-11d4-bdaf-00c04f60b9f0}"),
        dict(label="God Mode", command="start explorer.exe Shell:::{ED7BA470-8E54-465E-825C-99712043E01C}"),
        dict(label="Device Management", command="start devmgmt"),
        dict(label="Disk Management", command="start diskmgmt"),
        dict(label="Registry Editor", command="start regedit"),
    ],
    "Socials": [
        dict(label="Facebook", command="url www.facebook.com"),
        dict(label="Instagram", command="url www.instagram.com"),
        dict(label="Reddit", command="url www.reddit.com"),
        dict(label="Twitter", command="url www.twitter.com"),
        "---",
        dict(label="Telegram", command="url web.telegram.org"),
        dict(label="Whatsapp", command="url web.whatsapp.com"),
        dict(label="Discord", command="www.discord.com/app"),
        dict(label="Slack", command="url www.slack.com"),
        "---",
        dict(label="Tumblr", command="url www.tumblr.com"),
        dict(label="Pinterest", command="url www.pinterest.com"),
        dict(label="Linkedin", command="url www.linkedin.com"),
    ],
}
